# ~/.config/starship.toml

# Gruvbox
# gb.dark0_hard  = #1d2021
# gb.dark0       = #282828
# gb.dark0_soft  = #32302f
# gb.dark1       = #3c3836
# gb.dark2       = #504945
# gb.dark3       = #665c54
# gb.dark4       = #7c6f64
# gb.dark4_256   = #7c6f64
# gb.gray_245    = #928374
# gb.gray_244    = #928374
# gb.light0_hard = #f9f5d7
# gb.light0      = #fbf1c7
# gb.light0_soft = #f2e5bc
# gb.light1      = #ebdbb2
# gb.light2      = #d5c4a1
# gb.light3      = #bdae93
# gb.light4      = #a89984
# gb.light4_256  = #a89984
# gb.bright_red     = #fb4934
# gb.bright_green   = #b8bb26
# gb.bright_yellow  = #fabd2f
# gb.bright_blue    = #83a598
# gb.bright_purple  = #d3869b
# gb.bright_aqua    = #8ec07c
# gb.bright_orange  = #fe8019
# gb.neutral_red    = #cc241d
# gb.neutral_green  = #98971a
# gb.neutral_yellow = #d79921
# gb.neutral_blue   = #458588
# gb.neutral_purple = #b16286
# gb.neutral_aqua   = #689d6a
# gb.neutral_orange = #d65d0e
# gb.faded_red      = #9d0006
# gb.faded_green    = #79740e
# gb.faded_yellow   = #b57614
# gb.faded_blue     = #076678
# gb.faded_purple   = #8f3f71
# gb.faded_aqua     = #427b58
# gb.faded_orange   = #af3a03

# Use custom format
format = '''
[┌───────────────────>](bold green)$battery$time
[│](bold green)[](#f9f5d7)$os[](bg:#fb4934 fg:#f9f5d7)$username$hostname[](bg:#98971a fg:#fb4934)$directory[](bg:#d79921 fg:#98971a)$git_branch$git_status[](bg:#458588 fg:#d79931)$c$rust[](bg:#b16286 fg:#458588)$docker_context[](fg:#b16286)
[└─>](bold green)'''

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

# Disable the blank line at the start of the prompt
# add_newline = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
format = "[$symbol$name](bg:#f9f5d7 fg:#282828)"
disabled = false

[os.symbols]
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "﯑ "
Gentoo = " "
HardenedBSD = "ﲊ "
Illumos = " "
Linux = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = " "
openSUSE = " "
OracleLinux = " "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Redox = " "
Solus = "ﴱ "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = " "

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:#fb4934 fg:#282828"
style_root = "bg:#fb4934 fg:#282828"
format = '[$user@]($style)'
disabled = false

[hostname]
format = "[$hostname]($style)"
style = "bg:#fb4934 fg:#282828"
trim_at = "-"
ssh_only = false
disabled = false

[directory]
style = "bg:#98971a fg:#282828"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
symbol = ""
style = "bg:#d79921 fg:#282828"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#d79921 fg:#282828"
format = '[$all_status$ahead_behind ]($style)'

[rust]
symbol = ""
style = "bg:#458588 fg:#282828"
format = '[ $symbol ($version) ]($style)'

[c]
symbol = " "
style = "bg:#458588 fg:#282828"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#b16286 fg:#282828"
format = '[ $symbol $context ]($style) $path'

[battery]
full_symbol = "  "
charging_symbol = "  "
discharging_symbol = "  "
format = "[$symbol$percentage]()"

[[battery.display]]  # "bold red" style when capacity is between 0% and 10%
threshold = 20

[[battery.display]]  # "bold yellow" style when capacity is between 10% and 30%
threshold = 70

[[battery.display]]  # "bold green" style when capacity is between 10% and 30%
threshold = 100

[time]
disabled = false
time_format = "| %R" # Hour:Minute Format
format = '[ $time ]()'